### ISSUE TITLE
Datasources på lag som ikke vælges

### ISSUE THREAD

**Issue by jdgsolrod** [spatialsuite/qgis2sps#5]
Alle lag tages med i datasources - også de lag der ikke vælges i plugin’et. Altså hvis der er fire kompatible lag, og jeg vælger tre af dem i plugin’et, laves der datasources til alle fire kompatible lag. Der laves kun themes til de tre valgte lag.

**Comment by spatialsuite** [comment]
Det får jeg lige kigget på - den var dukket op under testen, men mente den var rettet. 
- Det bliver den lige igen !

/Morten

**Comment by spatialsuite** [comment]
Hej Jonas

Så skulle den gerne være rettet så den ikke skriver for mange datasources...

/Morten

**Comment by jdgsolrod** [comment]
Tak Morten. Det ser ud til at virke 👍
